language: python
services:
  - docker
before_install:
  - docker pull moss/xelatex
script:
 - mkdir out
 - docker-compose run jinja2cli cv.tex.j2 confidential.yaml > ./tex/cv_confidential.tex
 - docker-compose run jinja2cli cv.tex.j2 public.yaml > ./tex/cv.tex
 - docker-compose run xelatex -output-directory=/project/out cv_confidential.tex
 - docker-compose run xelatex -output-directory=/project/out cv.tex
after_success: ./publish.sh
