language: python
services:
  - docker
before_install:
  - docker pull thomasweise/texlive
script:
 - mkdir out
 - docker run -t -v `pwd`/out:/tmp/out thomasweise/texlive xelatex -output-directory=/tmp/out cv.tex
after_success: ./publish.sh